targets:
    linux:
        - name: debian-buster-x86_64
          platform: debian
          platform_version: buster
          family: debian
          runs_on: [self-hosted, linux, x64]
          docker_arch: linux/amd64
        - name: debian-buster-aarch64
          platform: debian
          platform_version: buster
          family: debian
          runs_on: [self-hosted, linux, arm64]
          docker_arch: linux/arm64
    macos:
        - name: macos-aarch64
          platform: macos
          platform_version: aarch64
          family: generic
          runs_on: [self-hosted, macOS, ARM64]
