<% from "tests.inc.yml" import build, calc_cache_key, restore_cache, setup_terraform -%>

name: Tests of patching old EdgeDB Versions

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - patch-test*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    <%- call build() -%>
    - name: Compute cache keys
      run: |
        << calc_cache_key()|indent >>
    <%- endcall %>

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        create-mode:
         - 'empty'
         #https://packages.edgedb.com/archive/x86_64-unknown-linux-gnu/edgedb-server-2.0+710b779.tar.gz
        edgedb-version:
         - '2.0+710b779'

    steps:
    <<- restore_cache() >>

    # Run the test

    - name: Download an earlier database version and set up a database
      env:
        EDGEDB_VERSION: ${{ matrix.edgedb-version }}
      run: |
        wget "https://packages.edgedb.com/archive/x86_64-unknown-linux-gnu/edgedb-server-$EDGEDB_VERSION.tar.gz"
        tar xzvf edgedb-server-$EDGEDB_VERSION.tar.gz
        edgedb-server-$EDGEDB_VERSION/bin/edgedb-server -D test-dir --bootstrap-only
    - name: Test
      # env:
      #   EDGEDB_TEST_POSTGRES_VERSION: ${{ matrix.postgres-version }}
      run: |
        edb test -j2 -v --data-dir test-dir
