[package]
name = "edgeql-parser"
version = "0.1.0"
license = "MIT/Apache-2.0"
authors = ["MagicStack Inc. <hello@magic.io>"]
edition = "2018"

[dependencies]
base32 = "0.4.0"
sha2 = "0.10.2"
snafu = "0.7.0"
combine = "4.6.3"
twoway = "0.2.2"
wasm-bindgen = { version="0.2.79", features=["serde-serialize"], optional=true }
serde = { version="1.0.136", features=["derive"], optional=true }
thiserror = "1.0.30"
unicode-width = "0.1.9"

[features]
default = []
wasm-lexer = ["wasm-bindgen", "serde"]

[lib]
