name: Build Test and Publish Nightly Packages

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - nightly

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: edgedb/edgedb-docker
        ref: master
        path: dockerfile

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Publish Docker Image
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: edgedb/edgedb
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "nightly,nightly_3-dev7435_cv202303300001"
        workdir: dockerfile
        buildargs: version=3-dev7435,exact_version=3.0-dev.7435,subdist=nightly
        platforms: linux/amd64,linux/arm64
