name: Tests

on:
  push:
    branches:
      - master
      - ci
      - "releases/*"
      - "stable/*"
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: "0 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: false

    - uses: actions/checkout@v3
      with:
        fetch-depth: 50
        submodules: true

    - name: Set up Python
      id: python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: |
          setup.py
          pyproject.toml

    - name: DEBUG
      shell: bash
      run: |
        set -e
        python -m pip install -U pip setuptools wheel build
        pip show build

    - name: pip list
      run: |
        pip list

  cargo-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: false

    - name: Set up Python
      id: python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: |
          setup.py
          pyproject.toml

    - name: Stop if we cannot retrieve the cache
      if: steps.python.outputs.cache-hit != 'true'
      run: |
        echo ::error::Cannot retrieve venv cache.
        exit 1

    - name: pip list
      run: |
        pip list

