name: Tests on PostgreSQL Versions

on:
  push:
    branches:
      - test-m1

jobs:
  test:
    runs-on: debian-aarch64
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: false

    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
        submodules: true

    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        default: true

    - name: Setup Python
      run: |
        sudo apt-get update
        sudo apt-get install -y make build-essential libssl-dev zlib1g-dev \
          libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
          libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
        git clone https://github.com/pyenv/pyenv.git ~/.pyenv
        ~/.pyenv/bin/pyenv install 3.10.0
        echo "PATH=$HOME/.pyenv/versions/3.10.0/bin/:$PATH" >> $GITHUB_ENV

    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install -y uuid-dev libreadline-dev bison flex

    - name: Run test
      env:
        EDGEDB_TEST_BACKEND_DSN: postgres://postgres:postgres@localhost/postgres
      run: |
        make
        edb test -j4 -v

  clean:
    runs-on: debian-aarch64
    needs: test
    if: ${{ always() }}
    steps:
      - run: sudo init 0
